on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
      go-version:
        type: string
        required: false
        default: 'oldstable'
      go-packages:
        type: string
        required: false
        default: './...' # or perhaps work
      show-coverage:
        description: Calculates a coverage PR comment grouped by all|module|root|package|file, or leave off
        type: string
        default: 'package' # all|module|root|package|file|off
      run-golangci-lint:
        description: Run golangci-lint; also implied by golangci-lint-config
        type: boolean
        required: false
        default: false
      golangci-lint-config:
        description: Optional path to a golangci-lint configuration file
        type: string
        required: false
jobs:
  run-tests:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    env:
      pkgs: ${{ inputs.go-packages }}
      variant: ${{ format('coverage-{0}-{1}', inputs.runs-on, inputs.go-version) }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ inputs.go-version }}
      - run: gofmt -s -w . && git diff --exit-code
      - run: go vet $pkgs
      - run: go mod tidy && git diff --exit-code
      - run: go mod download
      - run: go mod verify
      - run: go generate $pkgs && git diff --exit-code
      - run: go build -o /dev/null ${{ inputs.go-packages }}
      - run: go test -v -count=1 -shuffle=on -coverprofile=coverage.out -coverpkg="$pkgs" $pkgs
      - run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x -benchmem $pkgs
      - run: go run golang.org/x/vuln/cmd/govulncheck@latest -test $pkgs
      - uses: golangci/golangci-lint-action@v9
        with:
          args: ${{ hashFiles(inputs.golangci-lint-config) != '' && format('--config={0}', inputs.golangci-lint-config) || '' }}
        if: inputs.golangci-lint-config != '' || inputs.run-golangci-lint
      - if: inputs.show-coverage == 'all' || inputs.show-coverage == 'mod' || inputs.show-coverage == 'root' || inputs.show-coverage == 'pkg' || inputs.show-coverage == 'file'
        env:
          grouping: ${{ inputs.show-coverage }}
          base_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || '' }}
          base_sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
          branch_name: ${{ github.event.pull_request.head.ref || github.ref_name }}
          summary_url: ${{ format('{0}/{1}/actions/runs/{2}#summary-{3}', github.server_url, github.repository, github.run_id, job.check_run_id) }}
        run: |

          # validate coverage.out

          if ! [[ -f coverage.out ]]; then
            echo "::error::no coverage data at $(pwd)/coverage.out"
            exit 1
          fi

          # attempt to load base coverage, if in a PR

          if [[ -n "${base_sha-}" ]]; then
            if ! git fetch origin "$base_sha" --depth=1; then
              echo "::warning::unable to fetch $base_sha"
            elif ! git fetch origin "+refs/notes/*:refs/notes/*" --depth=1; then
              echo "::warning::unable to fetch coverage notes"
            elif base_coverage="$(git notes --ref go-$variant show "$base_sha" 2>/dev/null)"; then
              true
            elif base_coverage="$(git notes --ref go-coverage show "$base_sha" 2>/dev/null)"; then
              echo "::warning::using deprecated coverage notes for $base_sha"
            else
              base_coverage=""
              echo "::warning::unable to read coverage notes for $base_sha"
            fi
          fi

          # at this point we have ./coverage.out, our roots, and may have $base_coverage

          declare all_stmts=0 all_cov=0
          declare -A mod_stmts=() mod_cov=()
          declare -A root_stmts=() root_cov=()
          declare -A pkg_stmts=() pkg_cov=()
          declare -A file_stmts=() file_cov=()
          declare old_all_stmts=0 old_all_cov=0
          declare -A old_stmts=() old_cov=()

          while read -r loc count executed; do
            file="${loc%:*}"
            pkg="${file%/*}"
            if [[ "${lastpkg:-}" != "${pkg}" ]]; then
              pkgdir="$(go list -f '{''{.Dir}''}' "${pkg}" 2>/dev/null)"
              mod="$(cd "${pkgdir:-.}" && go list -m)"
              root="${pkg}"
              while [[ "${root}" != "${mod}" ]] && [[ "${root%/*}" != "${mod}" ]] && [[ "${root}" = *"/"* ]]; do
                root="${root%/*}"
              done
              lastpkg="${pkg}"
            fi
            (( all_stmts += count ))
            (( mod_stmts[$mod] += count ))
            (( root_stmts[$root] += count ))
            (( pkg_stmts[$pkg] += count ))
            (( file_stmts[$file] += count ))
            if (( executed > 0 )); then
              (( all_cov += count ))
              (( mod_cov[$mod] += count ))
              (( root_cov[$root] += count ))
              (( pkg_cov[$pkg] += count ))
              (( file_cov[$file] += count ))
            fi
          done < <(tail -n +2 coverage.out)

          # Summarize coverage.out with modules resolved. They may not be resolvable from a future HEAD.
          {
            echo "all:"
            echo "${GITHUB_REPOSITORY:-local} ${all_stmts:-0} ${all_cov:-0}"
            metrics() {
              local label=$1
              local -n stmts_ref="${1}_stmts"
              local -n cov_ref="${1}_cov"
              echo "$label:"
              for k in "${!stmts_ref[@]}"; do
                echo "${k} ${stmts_ref[$k]} ${cov_ref[$k]:-0}"
              done
            }
            metrics mod
            metrics root
            metrics pkg
            metrics file
          } > coverage.sum

          percent() { # 0 or undef => 0.00
            local div="$2"
            (( div > 0 )) && awk -v n="$1" -v d="$div" 'BEGIN { printf "%.2f", (n/d)*100 }' || echo "0.00"
          }
          delta() { # 0 => +0.00
            awk -v o="$1" -v n="$2" 'BEGIN { printf "%+.2f", (n-o) }'
          }

          # format our comment / job output as current stats, maybe with delta

          {
            # select stats
            case "$grouping" in
              (all) ;;
              (mod)
                declare label=Module
                declare -n stmts=mod_stmts
                declare -n cov=mod_cov
                ;;
              (root)
                declare label=Root
                declare -n stmts=root_stmts
                declare -n cov=root_cov
                ;;
              (pkg)
                declare label=Package
                declare -n stmts=pkg_stmts
                declare -n cov=pkg_cov
                ;;
              (file)
                declare label=File
                declare -n stmts=file_stmts
                declare -n cov=file_cov
                ;;
              (*) echo "::error::unknown grouping $grouping" && exit 1 ;;
            esac

            if [[ -z "${base_coverage:-}" ]]; then
              echo "Test coverage for **${branch_name:-HEAD}** (${GITHUB_SHA:-none}): **$(percent ${all_cov} ${all_stmts})%**"
              if [[ ${#stmts[@]} -gt 0 ]]; then
                echo
                echo "| $label | Coverage | Statements |"
                echo "|:--|--:|--:|"
                for k in "${!stmts[@]}"; do
                  echo "| ${k} | $(percent ${cov[$k]:-0} ${stmts[$k]:-0})% | ${cov[$k]:-0} of ${stmts[$k]} |"
                done | sort -u
                if [[ ${#stmts[@]} -gt 1 ]]; then
                  echo "| **Total** | $(percent ${all_cov} ${all_stmts})% | ${all_cov} of ${all_stmts} |"
                fi
              fi
            else
              while read -r prev_loc prev_stmts prev_cov; do
                if [[ "$prev_loc" == *":" ]]; then
                  ingroup="${prev_loc%:}"
                elif [[ "$ingroup" == "all" ]]; then
                  old_all_stmts="$prev_stmts"
                  old_all_cov="$prev_cov"
                elif [[ "$ingroup" == "$grouping" ]]; then
                  old_stmts[$prev_loc]="$prev_stmts"
                  old_cov[$prev_loc]="$prev_cov"
                fi
              done <<< "$base_coverage"
              npct="$(percent ${all_cov} ${all_stmts})"
              opct="$(percent ${old_all_cov} ${old_all_stmts})"
              echo "Test coverage change for **${base_ref:-BASE}** (${base_sha:-none}) to **${branch_name:-HEAD}** (${GITHUB_SHA:-none}): **${npct}%** ($(delta $opct $npct)%)"
              if [[ ${#stmts[@]} -gt 0 ]]; then
                echo
                echo "| $label | Coverage | Statements | Change | (Covered) | (Statements) |"
                echo "|:--|--:|--:|--:|--:|--:|"
                for k in "${!stmts[@]}" "${!old_stmts[@]}"; do
                  npct=$(percent ${cov[$k]:-0} ${stmts[$k]:-0})
                  opct=$(percent ${old_cov[$k]:-0} ${old_stmts[$k]:-0})
                  echo "| ${k} | $npct% | ${cov[$k]:-0} of ${stmts[$k]:-0} | $(delta $opct $npct) | (${opct}%) | (${old_cov[$k]:-0} of ${old_stmts[$k]:-0})|"
                done | sort -u
                if [[ ${#stmts[@]} -gt 1 ]]; then
                  npct="$(percent ${all_cov} ${all_stmts})"
                  opct="$(percent ${old_all_cov} ${old_all_stmts})"
                  echo "| **Total** | $npct% | ${all_cov} of ${all_stmts} | $(delta $opct $npct) | (${opct}%) | (${old_all_cov} of ${old_all_stmts})|"
                fi
              fi
            fi
          } | tee "${GITHUB_STEP_SUMMARY:-/dev/stderr}" > coverage.md
          {
            if [[ -z "${base_coverage:-}" ]]; then
              echo "Test coverage for **${branch_name:-HEAD}** (${GITHUB_SHA:-none}): [📊 **$(percent ${all_cov} ${all_stmts})%**]($summary_url)"
            else
              npct="$(percent ${all_cov} ${all_stmts})"
              opct="$(percent ${old_all_cov} ${old_all_stmts})"
              echo "Test coverage change for **${base_ref:-BASE}** (${base_sha:-none}) to **${branch_name:-HEAD}** (${GITHUB_SHA:-none}): [**${npct}%** ($(delta $opct $npct)%)]($summary_url)"
            fi
          } > coverage-link.md
      - uses: actions/upload-artifact@v7
        with:
          retention-days: 3
          overwrite: true
          name: ${{ env.variant }}
          path: |
            coverage.out
            coverage.sum
            coverage.md
            coverage-link.md
